// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrCzOw5KA65rSxi2yYhVZuhCHxtS1izSM',
    appId: '1:1003399577030:web:2290ce3cb0a690ad46c6c7',
    messagingSenderId: '1003399577030',
    projectId: 'whatsappchat-991ef',
    authDomain: 'whatsappchat-991ef.firebaseapp.com',
    storageBucket: 'whatsappchat-991ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29c_isxA4CRZ5EzZ9rAPjPIcfly0ERxg',
    appId: '1:1003399577030:android:f0288e3acafdcb6f46c6c7',
    messagingSenderId: '1003399577030',
    projectId: 'whatsappchat-991ef',
    storageBucket: 'whatsappchat-991ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiIjtZfv9i9twtVHR2kN_ZmoKDGgruecQ',
    appId: '1:1003399577030:ios:d70cc11ffbb305a346c6c7',
    messagingSenderId: '1003399577030',
    projectId: 'whatsappchat-991ef',
    storageBucket: 'whatsappchat-991ef.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiIjtZfv9i9twtVHR2kN_ZmoKDGgruecQ',
    appId: '1:1003399577030:ios:d70cc11ffbb305a346c6c7',
    messagingSenderId: '1003399577030',
    projectId: 'whatsappchat-991ef',
    storageBucket: 'whatsappchat-991ef.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
